# GitHub Actions training


name: Project-workflow
  
  
on:
  push:
    branches:
      - master
      
      
jobs:
  deploy:
    runs-on: ubuntu-latest
       
    steps:
      - name: Initial deploy
      -  run: node --version
      -  run: npm --version
      -  run: echo "Initialization workflow for deploy"
         
